import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import styles from "../styles/Home.module.css";
import Main from "../components/main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App {styles.container}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/@themesberg/flowbite@1.3.0/dist/flowbite.min.css"
        />
        <script src="../path/to/flowbite/dist/flowbite.js"></script>
      </Head>
      <Navbar />
      <Main />
    </div>
  );
}
